apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester-worker
  template:
    metadata:
      labels:
        app: load-tester-worker
    spec:
      containers:
        - name: load-tester-worker
          image: load-tester-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: aws-sqs-credentials
          volumeMounts:
            - name: db-storage
              mountPath: /data
          env:
            - name: DB_PATH
              value: "/data/load_tests.db"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: load-tester-db-pvc